{% set name = "pytest-mypy-plugins" %}
{% set version = "3.3.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4faa42c567fc25951f065c42607f61f5c36ded0265f4d77a4d16cda76002054a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2
    - decorator
    - mypy >=1.3
    - pytest >=7.0
    - pyyaml
    - regex
    - packaging
    - tomlkit >=0.11
    - jsonschema

test:
  imports:
    - pytest_mypy_plugins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/TypedDjango/pytest-mypy-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for writing tests for mypy plugins
  doc_url: https://pypi.org/project/pytest-mypy-plugins/
  dev_url: https://github.com/TypedDjango/pytest-mypy-plugins

extra:
  recipe-maintainers:
    - sobolevn
    - zero323
