{% set name = "pytest-mypy-plugins" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2c6590ee68fd634013fdd0b47a5c83df300afd8b38d5aabd3b29e21b7907221

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - chevron
    - dataclasses
    - decorator
    - mypy >=0.790
    - pytest >=6.0.0
    - python >=3.6
    - pyyaml
    - regex

test:
  imports:
    - pytest_mypy_plugins

about:
  home: https://github.com/TypedDjango/pytest-mypy-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for writing tests for mypy plugins
  doc_url: https://pypi.org/project/pytest-mypy-plugins/
  dev_url: https://github.com/TypedDjango/pytest-mypy-plugins

extra:
  recipe-maintainers:
    - sobolevn
    - zero323
