{% set name = "pytest-mypy-plugins" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10b51b8b6d6573589d5c1482ced943efa2571df842749cbb2a2446d82c710a49

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - chevron
    - dataclasses
    - decorator
    - mypy >=0.970
    - pytest >=6.2
    - python >=3.6
    - pyyaml
    - regex
    - packaging

test:
  imports:
    - pytest_mypy_plugins

about:
  home: https://github.com/TypedDjango/pytest-mypy-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for writing tests for mypy plugins
  doc_url: https://pypi.org/project/pytest-mypy-plugins/
  dev_url: https://github.com/TypedDjango/pytest-mypy-plugins

extra:
  recipe-maintainers:
    - sobolevn
    - zero323
