{% set name = "pytest-mypy-plugins" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8146115f9b4bed02b299465a2c2b9326b367ea64b155e9d77562769af963d01b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - jinja2
    - decorator
    - mypy >=1.3
    - pytest >=7.0
    - python >=3.7
    - pyyaml
    - regex
    - packaging
    - tomlkit >=0.11

test:
  imports:
    - pytest_mypy_plugins

about:
  home: https://github.com/TypedDjango/pytest-mypy-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin for writing tests for mypy plugins
  doc_url: https://pypi.org/project/pytest-mypy-plugins/
  dev_url: https://github.com/TypedDjango/pytest-mypy-plugins

extra:
  recipe-maintainers:
    - sobolevn
    - zero323
